// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FlexProviders.Tests.Integration.EF.Migrations
{
    public sealed partial class Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201209221621381_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
